[tasks."apply:dotfiles"]
run = "chezmoi apply -c chezmoi.yaml --force"

[tasks.diff]
run = "chezmoi diff -c chezmoi.yaml"

[tasks."apply:winget"]
run = [
    "yq configs/.winget/packages.yaml -o json > configs/.winget/packages.json",
    "winget pin reset --force",
    "winget import configs/.winget/packages.json",
    "winget pin add Autohotkey.AutoHotkey",
    "del /q %USERPROFILE%\\Desktop\\*.lnk",
]
