pscmd := "powershell -NoProfile -ExecutionPolicy Bypass -Command"

win11debloat-cmd := "& ([scriptblock]::Create((irm 'https://debloat.raphi.re/')))"
win11debloat:
  cp -r ./undotfiles/debloat/Win11Debloat ${TEMP}
  {{pscmd}} "{{win11debloat-cmd}}" -RunSavedSettings -RemoveAppsCustom -Silent

winutil-cmd := "& ([scriptblock]::Create((irm 'https://christitus.com/win')))"
winutil-config := "${PWD}/undotfiles/debloat/Winutil/winutil.config.json"
winutil:
  {{pscmd}} "{{winutil-cmd}}" -Config {{winutil-config}} -Run

highPerfPlan := "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
setup-powerplan:
  powercfg /setactive {{highPerfPlan}}
  powercfg /change monitor-timeout-ac 0
  powercfg /change monitor-timeout-dc 0