// Bootstrap system packages and CLI tools for this dotfiles setup.
// Everything except plain apt prerequisites is generated into a temporary
// Brewfile from the package lists below and applied via `brew bundle`
// (Homebrew on Linux + Flathub).
// No version management: every tool installs/updates to its latest release.
// Prerequisites, installed by setup.sh: Homebrew on Linux and bun.
//
// Run with `bun undotfiles/bootstrap.ts` (or `just install`).

import { existsSync } from "node:fs";
import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";

const FLATHUB_REPO_URL = "https://dl.flathub.org/repo/flathub.flatpakrepo";

// Homebrew on Linux official installer default. Only this path is hardcoded:
// PATH lookup may miss brew when this runs outside setup.sh's shellenv.
const BREW_FALLBACK_DIR = "/home/linuxbrew/.linuxbrew";

// Android SDK install target of the sdkmanager postinstall in the Brewfile.
const SDK_DIR = join(homedir(), ".android-sdk");

// Plain apt prerequisites, kept outside the generated Brewfile.
const APT_PACKAGES = [
  "flatpak", // used by the Brewfile `flatpak` entries
  "fonts-noto-cjk",
  "libasound2t64",
  "xvfb",
];

// Package lists: fed into the generated Brewfile, grouped by `brew bundle`
// DSL type. Order matters: formulae come first (runtimes listed early), then
// npm/uv/go entries which need those runtimes.

export type PackageLists = {
  brewFormulae: string[];
  npmPackages: string[];
  uvTools: string[];
  goPackages: string[];
};

export const PACKAGE_LISTS = {
  brewFormulae: [
    // system packages
    "bubblewrap",
    "ffmpeg",
    "git",
    "powershell",
    "socat",
    "tmux",
    "unzip",
    // language runtimes (npm/uv/go entries depend on these)
    "bun",
    "go",
    "node",
    "rustup",
    "uv",
    // LLM-only CLI tools
    "ast-grep",
    "code2prompt",
    "dasel",
    "difftastic",
    "hyperfine",
    "jq",
    "keep-sorted",
    "pdfcpu",
    "rtk",
    "sd",
    "shellcheck",
    "shfmt",
    "watchexec",
    // general CLI tools
    "act",
    "cargo-binstall",
    "chezmoi",
    "erdtree",
    "eza",
    "fd",
    "gh",
    "git-cliff",
    "gopls",
    "just",
    "just-lsp",
    "mise",
    "nixfmt",
    "pandoc",
    "ripgrep",
    "tokei",
    "tree-sitter-cli",
    "yq",
  ],
  npmPackages: [
    // standalone tools (vp / vpr / oxfmt / oxlint via vite-plus)
    "vite-plus",
    // LLM-only CLI tools
    "@earendil-works/pi-coding-agent",
    "agent-browser",
    "cursor-agent",
    "officecli",
    // general CLI tools
    "@typescript/native-preview", // tsgo / tsgolint
  ],
  uvTools: [
    // LLM-only CLI tools
    "trafilatura[all]",
    "mineru[all]",
    // general CLI tools
    "harlequin",
  ],
  goPackages: [
    // LLM-only CLI tools
    "github.com/karust/openserp",
  ],
} satisfies PackageLists;

async function main(): Promise<void> {
  log("apt prerequisites");
  ensureAptPackages(APT_PACKAGES);

  log("homebrew");
  const brew = setupBrew();
  await brewBundle(brew);
  ensureRustupToolchain();
}

function ensureAptPackages(pkgs: string[]): void {
  const missing = pkgs.filter((pkg) => !commandSucceeded(["dpkg", "-s", pkg]));
  if (missing.length === 0) return;
  run(["sudo", "apt", "update"]);
  for (const pkg of missing) {
    run(["sudo", "apt", "install", "-y", pkg]);
  }
}

type Brew = { bin: string; prefix: string };

// Finds brew's executable and prefix, and puts brew's bin dir on PATH (the
// `brew shellenv` equivalent) so brew-installed CLIs like rustup resolve.
function setupBrew(): Brew {
  const bin = Bun.which("brew") ?? `${BREW_FALLBACK_DIR}/bin/brew`;
  if (!existsSync(bin)) {
    throw new Error(`brew not found at ${bin}; run setup.sh first to install Homebrew`);
  }
  const prefix = Bun.spawnSync([bin, "--prefix"], { stdout: "pipe" }).stdout.toString().trim();
  process.env.PATH = `${prefix}/bin:${process.env.PATH ?? ""}`;
  return { bin, prefix };
}

async function brewBundle(brew: Brew): Promise<void> {
  const brewfileDir = await mkdtemp(join(tmpdir(), "bootstrap-"));
  const brewfilePath = join(brewfileDir, "Brewfile");
  try {
    await writeFile(brewfilePath, generateBrewfile(PACKAGE_LISTS, brew.prefix));
    run([brew.bin, "bundle", `--file=${brewfilePath}`]);
  } finally {
    await rm(brewfileDir, { recursive: true, force: true });
  }
}

export function generateBrewfile(lists: PackageLists, brewPrefix: string): string {
  const sdkmanager = `${brewPrefix}/bin/sdkmanager`;
  const acceptLicenses = `yes | ${sdkmanager} --sdk_root=${SDK_DIR} --licenses >/dev/null`;
  const installSdkPackages = `${sdkmanager} --sdk_root=${SDK_DIR} 'cmdline-tools;latest' 'platform-tools' >/dev/null`;
  return [
    "# Generated by undotfiles/bootstrap.ts -- edit the package lists in the script, not this file.",
    ...dslEntries("brew", lists.brewFormulae),
    `flatpak "com.google.Chrome", url: "${FLATHUB_REPO_URL}"`,
    'cask "drawio"',
    `cask "android-commandlinetools", postinstall: "${acceptLicenses} && ${installSdkPackages}"`,
    ...dslEntries("npm", lists.npmPackages),
    ...dslEntries("uv", lists.uvTools),
    ...dslEntries("go", lists.goPackages),
    "",
  ].join("\n");
}

type BrewfileDslType = "brew" | "npm" | "uv" | "go";

function dslEntries(dslType: BrewfileDslType, entries: string[]): string[] {
  return entries.map((entry) => `${dslType} "${entry}"`);
}

function ensureRustupToolchain(): void {
  if (commandSucceeded(["rustup", "default"])) return;
  run(["rustup", "default", "stable"]);
}

function log(message: string): void {
  console.log(`\x1b[1;32m==>\x1b[0m ${message}`);
}

function run(command: string[]): void {
  const proc = Bun.spawnSync(command, { stdout: "inherit", stderr: "inherit" });
  if (proc.exitCode !== 0) {
    throw new Error(`command failed (exit ${proc.exitCode}): ${command.join(" ")}`);
  }
}

// Reports whether a probe command succeeded, without any output.
function commandSucceeded(command: string[]): boolean {
  return Bun.spawnSync(command, { stdout: "ignore", stderr: "ignore" }).exitCode === 0;
}

if (import.meta.main) {
  await main();
}
