#!/usr/bin/env bash
# Bootstrap system packages and CLI tools for this dotfiles setup.
# Everything except plain apt prerequisites is generated into a temporary
# Brewfile from the package lists below and applied via `brew bundle`
# (Homebrew on Linux + Flathub).
# No version management: every tool installs/updates to its latest release.
set -euo pipefail

# Homebrew on Linux official installer default. Only this path is hardcoded:
# `brew --prefix` needs a working brew, which we may not have yet.
BREW_BIN="/home/linuxbrew/.linuxbrew/bin/brew"
SDK_DIR="$HOME/.android-sdk"
FLATHUB_REPO_URL="https://dl.flathub.org/repo/flathub.flatpakrepo"
APT_UPDATED=0

# region package lists
# Fed into the generated Brewfile, grouped by `brew bundle` DSL type.
# Order matters: formulae come first (runtimes listed early), then npm/uv/go
# entries which need those runtimes.

BREW_FORMULAE=(
  # system packages
  bubblewrap
  ffmpeg
  git
  powershell
  socat
  tmux
  unzip
  # language runtimes (npm/uv/go entries depend on these)
  bun
  go
  node
  rustup
  uv
  # LLM-only CLI tools
  ast-grep
  code2prompt
  dasel
  difftastic
  hyperfine
  jq
  keep-sorted
  pdfcpu
  rtk
  sd
  shellcheck
  shfmt
  watchexec
  # general CLI tools
  act
  cargo-binstall
  chezmoi
  erdtree
  eza
  fd
  gh
  git-cliff
  gopls
  just
  just-lsp
  mise
  nixfmt
  pandoc
  ripgrep
  tokei
  tree-sitter-cli
  yq
)

NPM_PACKAGES=(
  # standalone tools (vp / vpr / oxfmt / oxlint via vite-plus)
  vite-plus
  # LLM-only CLI tools
  "@earendil-works/pi-coding-agent"
  agent-browser
  cursor-agent
  officecli
  # general CLI tools
  "@typescript/native-preview" # tsgo / tsgolint
)

UV_TOOLS=(
  # LLM-only CLI tools
  "trafilatura[all]"
  "mineru[all]"
  # general CLI tools
  harlequin
)

GO_PACKAGES=(
  # LLM-only CLI tools
  github.com/karust/openserp
)

# endregion

# region functions

# --- helpers ------------------------------------------------------------------

log() { printf '\033[1;32m==>\033[0m %s\n' "$*"; }

# --- apt prerequisites (no brew equivalent) -----------------------------------

apt_update_once() {
  [[ $APT_UPDATED -eq 0 ]] || return 0
  sudo apt update
  APT_UPDATED=1
}

ensure_apt() {
  dpkg -s "$1" >/dev/null 2>&1 && return 0
  apt_update_once
  sudo apt install -y "$1"
}

# --- homebrew -----------------------------------------------------------------

setup_brew_env() {
  eval "$("$BREW_BIN" shellenv)"
}

ensure_brew() {
  [[ -x "$BREW_BIN" ]] && return 0
  NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

ensure_rustup_toolchain() {
  rustup default >/dev/null 2>&1 && return 0
  rustup default stable
}

# --- generated Brewfile -------------------------------------------------------

emit_dsl_entries() {
  local type=$1 entry
  shift
  for entry in "$@"; do
    printf '%s "%s"\n' "$type" "$entry"
  done
}

write_brewfile() {
  local out=$1 prefix=$2
  local sdk="$prefix/bin/sdkmanager"
  local accept_licenses="yes | $sdk --sdk_root=$SDK_DIR --licenses >/dev/null"
  local install_pkgs="$sdk --sdk_root=$SDK_DIR 'cmdline-tools;latest' 'platform-tools' >/dev/null"

  {
    printf '# Generated by undotfiles/bootstrap.sh -- edit the package lists in the script, not this file.\n'
    emit_dsl_entries brew "${BREW_FORMULAE[@]}"
    printf 'flatpak "com.google.Chrome", url: "%s"\n' "$FLATHUB_REPO_URL"
    printf 'cask "drawio"\n'
    printf 'cask "android-commandlinetools", postinstall: "%s && %s"\n' "$accept_licenses" "$install_pkgs"

    emit_dsl_entries npm "${NPM_PACKAGES[@]}"
    emit_dsl_entries uv "${UV_TOOLS[@]}"
    emit_dsl_entries go "${GO_PACKAGES[@]}"
  } >"$out"
}

brew_bundle() {
  local brewfile
  brewfile=$(mktemp)
  write_brewfile "$brewfile" "$(brew --prefix)"
  brew bundle --file="$brewfile"
  rm -f "$brewfile"
}

# endregion

# ==============================================================================
# apt prerequisites (no brew equivalent)
# ==============================================================================

log "apt prerequisites"

ensure_apt build-essential # Homebrew on Linux build prerequisite
ensure_apt flatpak         # Brewfile `flatpak` entries use it
ensure_apt fonts-noto-cjk
ensure_apt git             # Homebrew installer prerequisite
ensure_apt libasound2t64
ensure_apt xvfb

# ==============================================================================
# Homebrew (formulae, casks, npm, uv, go, flatpak via generated Brewfile)
# ==============================================================================

log "homebrew"

ensure_brew
setup_brew_env
brew_bundle
ensure_rustup_toolchain
