_winconfig:
  just win11debloat
  just winutil
  just my-custom

win11debloat_cmd := "& ([scriptblock]::Create((irm 'https://debloat.raphi.re/')))"
win11debloat:
  cp -r ./undotfiles/winconfig/Win11Debloat $env.TEMP
  {{run_ps_cmd}} "{{win11debloat_cmd}}" -RunSavedSettings -RemoveAppsCustom -Silent

winutil_cmd := "& ([scriptblock]::Create((irm 'https://christitus.com/win')))"
winutil_config := "($env.PWD)/undotfiles/winconfig/Winutil/winutil.config.json"
winutil:
  {{run_ps_cmd}} "{{winutil_cmd}}" -Config {{winutil_config}} -Run

my-custom:
  {{run_ps_file}} "undotfiles/winconfig/my-custom.ps1"
