_winconfig:
  just win11debloat
  just winutil
  just setup-powerplan

win11debloat_cmd := "& ([scriptblock]::Create((irm 'https://debloat.raphi.re/')))"
win11debloat:
  cp -r ./undotfiles/winconfig/Win11Debloat $env.TEMP
  {{run_ps_cmd}} "{{win11debloat_cmd}}" -RunSavedSettings -RemoveAppsCustom -Silent

winutil_cmd := "& ([scriptblock]::Create((irm 'https://christitus.com/win')))"
winutil_config := "($env.PWD)/undotfiles/winconfig/Winutil/winutil.config.json"
winutil:
  {{run_ps_cmd}} "{{winutil_cmd}}" -Config {{winutil_config}} -Run

highPerfPlan := "8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c"
setup-powerplan:
  powercfg /setactive {{highPerfPlan}}
  powercfg /change monitor-timeout-ac 0
  powercfg /change monitor-timeout-dc 0
